### ISSUE TITLE
Error building Player: Incompatible color space with graphics API

### ISSUE THREAD

**Issue by Tyson-Wu** [superunitybuild/buildtool#100]
when i set linear color space for android platform, build for android throw the error:
"Error building Player: Incompatible color space with graphics API"
i fix this by add a simple line:
AssetDatabase.SaveAssets();
in the BuildProject.cs before invoke BuildPipeline.BuildPlayer

**Comment by MatthieuG9** [comment]
Same issue here with Unity 2022.x

**Comment by MatthieuG9** [comment]
Here the PR : https://github.com/superunitybuild/buildtool/pull/118

**Comment by robinnorth** [comment]
Fixed in #118
