### ISSUE TITLE
Fix for #89 (wrong enum type on macOS) was reverted

### ISSUE THREAD

**Issue by chemicalcrux** [superunitybuild/buildtool#109]
Issue #89 was fixed by pull request #94 . However, the fix got reverted by commit d26db72a54064f45f60a3fe5fc77c4130a815ed1. It looks like the wrong line got kept.

**Comment by robinnorth** [comment]
Thanks for spotting this @chemicalcrux, I've just fixed this in  [v6.0.1].(https://github.com/superunitybuild/buildtool/releases/tag/v6.0.1)
