### ISSUE TITLE
Unity 2020.3 - Some c# runtimes appears to not be compatible

### ISSUE THREAD

**Issue by IanGallacher** [superunitybuild/buildtool#111]
I'm attempting to use the latest SuperUnityBuild in unity 2020.3, and I get an error saying something along the lines of `String.join` is not able to convert from 'char' to 'string'.

I'm trying to use mono and .net 4.0.

Are not all C# versions/frameworks available in unity 2020.3 supported by super unity build? If they are, it would not be a large PR to fix. If they are not, I'd consider updating the README to mention what is supported.

**Comment by RobProductions** [comment]
I noticed this actually and already fixed it in my personal fork where I'm doing some other UX changes and fixes. Specifically, it was a dependency on .NET Standard 2.1 whereas Unity 2020.3 still supports Standard 2.0. I should have a PR ready in just a few days that addresses it :) in the meantime I believe previous versions of SuperUnityBuild don't have the same issue

**Comment by robinnorth** [comment]
This is fixed in [v7.0.0](https://github.com/superunitybuild/buildtool/releases/tag/v7.0.0), thanks to @RobProductions in #113 🥳
