### ISSUE TITLE
Errors when importing in a clean project

### ISSUE THREAD

**Issue by Sterling-Malory-Archer** [superunitybuild/buildtool#127]
Hi everyone, I am using Unity 2020.326f1 LTS and when I import the project through the git URL I get these errors:

`Library\PackageCache\com.github.superunitybuild.buildtool@e180f89f3c\Editor\Build\Platform\BuildAndroid.cs(98,26): error CS1061: 'IEnumerable<string>' does not contain a definition for 'SkipLast' and no accessible extension method 'SkipLast' accepting a first argument of type 'IEnumerable<string>' could be found (are you missing a using directive or an assembly reference?)
`

`Library\PackageCache\com.github.superunitybuild.buildtool@e180f89f3c\Editor\Build\Platform\BuildVariant.cs(27,45): error CS1503: Argument 1: cannot convert from 'char' to 'string'`

`Library\PackageCache\com.github.superunitybuild.buildtool@e180f89f3c\Editor\Build\Platform\BuildVariant.cs(67,41): error CS1503: Argument 1: cannot convert from 'char' to 'string'`

Any help is greatly appreciated. I have imported BuildActions as well.

**Comment by RobProductions** [comment]
Hi, I believe this is a duplicate of #111 so check out that trail for more info. The fix has been merged (into the dev branch I think?) but was not released under a new tag yet.
