### ISSUE TITLE
Unity windows not closing until the very end

### ISSUE THREAD

**Issue by tvogt** [superunitybuild/buildtool#145]
Seems that something changed recently, maybe in Unity. I now have the funny feature that all the Unity processing windows stay open until all the builds (8 for me, different platforms and distribution channels) are complete.

Which leads to:
<img width="1524" alt="Bildschirmfoto 2024-08-04 um 14 22 22" src="https://github.com/user-attachments/assets/043dcb7a-7d4f-4947-b4b0-9dfd5c1d9beb">

**Comment by robinnorth** [comment]
Oh, fun! What Unity version is this happening on?
