### ISSUE TITLE
Enabling an action after disabling it prior stops it from being performed

### ISSUE THREAD

**Issue by theBrandonWu** [superunitybuild/buildtool#32]
I noticed that after I disabled a Post-build action (in this case, UploadItch), when I enabled it again, the action would still be skipped. 

Adding a new action and copying over the properties works. 

Anyone else seeing the same thing?

**Comment by Chaser324** [comment]
I'll take a look at this. It's possible that it may just not be triggering
the SerializedObject to be saved (although if disabling does work, that may
not be the case).

What version of Unity are you on?

**Comment by theBrandonWu** [comment]
Woot quick reply! I am on 2018.1.3f1. I tried saving, restarting Unity, and the issue persists. Not a big problem, just took a bit of time to figure out why it wasn't uploading - thought it was a problem with butler. :)

**Comment by robinnorth** [comment]
Closing, as this is no longer happening on 1.0.0-pre.1. Do feel free to re-open if you find the issue persists for you after updating your SuperUnityBuild version.
