### ISSUE TITLE
Custom build paths

### ISSUE THREAD

**Issue by malkere** [superunitybuild/buildtool#34]
An option to easily specify the results of $ARCHITECTURE in the build path settings would be nice. A simple wiki entry as to where and how the variables are stored would be enough. For example changing "Windows x86" to "Win32".

**Comment by malkere** [comment]
Changing the BuildPC scripts worked fine. Just had to remake the settings file.

**Comment by robinnorth** [comment]
Closing this in favour of sticking to the current architecture naming.
