### ISSUE TITLE
BuildAddressables issues

### ISSUE THREAD

**Issue by allansimonsen** [superunitybuild/buildtool#54]
I'm struggling to get BuildAddressables working properly. Occasionally I'm seeing the wrong Addressable sets copied when building multiple platforms; OSX getting the Android addressables, etc). BuildAddressables is tagged as a pre-build action.

**Comment by robinnorth** [comment]
@allansimonsen what is BuildAddressables, exactly? Is it a custom Build Action you've written yourself?

**Comment by dozd** [comment]
I am having this issue as well.

@robinnorth BuildAddressables is the "new" system unity is using for async loading of the assets: https://docs.unity3d.com/Packages/com.unity.addressables@0.4/manual/index.html

I am trying to include the build of Addressables into the SuperUnityBuild by calling `AddressableAssetSettings.BuildPlayerContent();` before the build but still can't figure out why the output is being mixed between the platforms :(.

**Comment by dozd** [comment]
Maybe I got it working and integrated into SuperUnityBuild. I'll do some more testing before creating a pull request

`BuildProject.cs`
![image](https://user-images.githubusercontent.com/306734/109974658-11f6fe80-7cfa-11eb-8cf2-055d8e735dda.png)

Here the code you can try @allansimonsen 
```
        // Build addressables
        #if UNITY_5_6_OR_NEWER
            EditorUserBuildSettings.SwitchActiveBuildTarget(platform.targetGroup, architecture.target);
        #else
            EditorUserBuildSettings.SwitchActiveBuildTarget(arch.target);
        #endif
        
        AddressableAssetSettings.BuildPlayerContent();     
```

**Comment by dozd** [comment]
It's working great for me! Need a test on a project without addressables enabled

https://github.com/Chaser324/unity-build/pull/64

**Comment by robinnorth** [comment]
Closing in favour of creating an Addressables BuildAction, as per [#64 (comment)](https://github.com/superunitybuild/buildtool/issues/64#issuecomment-792231244)
