### ISSUE TITLE
Linux build does not work

### ISSUE THREAD

**Issue by zephyo** [superunitybuild/buildtool#55]
Although I have Linux enabled, it doesn't build to linux.
<img width="548" alt="Screen Shot 2020-05-07 at 1 52 35 PM" src="https://user-images.githubusercontent.com/22963510/81327933-0bf8a880-906a-11ea-8f99-28722b985167.png">
It also doesn't show that there are 6 enabled builds as opposed to 4 (Mac and Windows for two releases).
<img width="553" alt="Screen Shot 2020-05-07 at 1 52 44 PM" src="https://user-images.githubusercontent.com/22963510/81327938-0d29d580-906a-11ea-9c34-32bfc5ccbb60.png">

**Comment by robinnorth** [comment]
@zephyo is this still happening? If so, can you confirm your Unity version, if there are any errors in your Console and that you're using SuperUnityBuild checked out from the `master` branch of this repo? The last published version is rather out of date now.

**Comment by robinnorth** [comment]
@zephyo building for Linux is working for me on 1.0.0-pre.1 using Unity 2020.3, and Linux build configurations are showing up in the builds list for me, so I'm going to close this issue, but do feel free to reopen if the problem still occurs for you after updating your SuperUnityBuild version.

![image](https://user-images.githubusercontent.com/3787255/114370214-20e19400-9b77-11eb-9629-fad28037a3ce.png)
