### ISSUE TITLE
Post build actions per distribution

### ISSUE THREAD

**Issue by the-mr-matt** [superunitybuild/buildtool#57]
Is it possible to perform a post build action after each distribution rather than waiting for the entire thing to finish? I have a post build action that uploads the build to Steamworks, and another that uploads to GOG Galaxy. Both actions happen at the same time and the Steamworks cmd tool interferes with GOG Galaxy so I always have to launch one manually afterwards.

**Comment by robinnorth** [comment]
@the-mr-matt have you tried using Per Platform post-build actions and using filters to target only the distribution you're interested in? They run immediately after each individual build configuration, rather than after all build configurations.
