### ISSUE TITLE
$VERSION is empty if "Sync version with player settings" is checked

### ISSUE THREAD

**Issue by TMaloteaux** [superunitybuild/buildtool#73]
sb.Replace("$VERSION", SanitizeFolderName(**BuildSettings.productParameters.lastGeneratedVersion**));

should probably use Application.version when "Sync version with player settings" is checked

**Comment by robinnorth** [comment]
Thanks for spotting this! Because `BuildSettings.productParameters.lastGeneratedVersion` is also used by some BuildActions to get the build version number, I will update it when 'Sync version with Player settings' is checked, which should then fix the issue.
