### ISSUE TITLE
Ability to change root folder of settings.

### ISSUE THREAD

**Issue by vailshnast** [superunitybuild/buildtool#76]
Would be amazing to add ability to change root folder. Package does have constants with folder paths, but you cant change them, thanks! Something like to Plugins/SuperUnityBuild etc.

**Comment by tycobbb** [comment]
@robinnorth i think this is still an issue. we've moved the `SuperUnityBuild` folder to `Assets/Plugins` and pointed the plugin to the settings in `Assets/Plugins/SuperUnityBuild/Settings`, but every time we build it re-creates the default folder and settings asset and re-sets the path to the freshly created asset.

**Comment by robinnorth** [comment]
Just tested this again and #116 appears to have solved this. Moving `/Assets/SuperUnityBuild` to  `/Assets/Test/SuperUnityBuild` and re-pointing the settings asset path to `/Assets/Test/SuperUnityBuild/Settings/SuperUnityBuildSettings.asset` worked as expected for both configuring the Editor environment and building.
