### ISSUE TITLE
Show Notes/Allow naming of individual Pre/Post Build Actions

### ISSUE THREAD

**Issue by muskieratboi** [superunitybuild/buildtool#77]
Right now, when performing multiple Pre or post build actions (say, for switching between XR plugins, or performing file operations),
The list of actions simply shows the type of action being performed:

![](https://i.imgur.com/GeDMunE.png)

Would it be possible to Append the text in the "Note" section to the title bar, so users can check which particular build action is which at a glance, without having to go through each one?

**Comment by robinnorth** [comment]
Thanks for the suggestion @muskieratboi, making use of the 'Note' text in the title of the build actions would be very useful indeed.

**Comment by robinnorth** [comment]
@muskieratboi I have implemented your suggestion, you can check out the latest commit from `dev` to test it out, if you like. It'll be included in the next released version of the package, along with a similar change for showing selected architectures and variants in the Build Platform list view.

![image](https://user-images.githubusercontent.com/3787255/141284603-0a351e99-abb3-440e-aeba-e550e2bbdf71.png)
