### ISSUE TITLE
Customize scenes per platform

### ISSUE THREAD

**Issue by angelhodar** [superunitybuild/buildtool#80]
Hey! First of all thank you for your effort creating this amazing package. I have been using it to speed up my build pipeline for different platforms and my team and I are wondering if it is possible to select which scenes are built for a platform in a release. This is because we are used to create a Preload scene with prefabs unique for a custom platform, which gives as more flexibility to integrate. For example, if a release has windows and android support, we would like to add the PreLoadWindows scene for windows platform in that release and PreLoadAndroid for android. Would it be possible to integrate in the tool or it could be implemented by creating a custom action?

Thanks in advance!!

**Comment by robinnorth** [comment]
Thanks @angelhodar! To implement per-platform scenes for each release type would probably require some major architectural changes to the tool.

However, I think it should be possible to achieve what you want to do with build actions -- you could write a custom pre-build action that added a specific scene to a release type's scene list (`BuildReleaseType.sceneList.enabledScenes`) in its `PerBuildExecute` method and a corresponding post-build action that removed the added scene.

Alternatively you could have a single preload scene and use a custom scene processor script that uses the [`IProcessSceneWithReport`](https://docs.unity3d.com/ScriptReference/Build.IProcessSceneWithReport.html) interface to remove scene objects in the [`OnProcessScene`](https://docs.unity3d.com/ScriptReference/Build.IProcessSceneWithReport.OnProcessScene.html) callback for the script, based on the value of `BuildReport.summary.platform` of the `BuildReport` the callback is passed. Here's an example of someone doing something similar: https://gamedev.stackexchange.com/a/174332.

Hope this is helpful!
