### ISSUE TITLE
Ability to list all connected Android devices?

### ISSUE THREAD

**Issue by Sebight** [superunitybuild/buildtool#86]
Hello, 

I've only skimmed through the wiki very fast, but haven't found any mention of what I'm searching for.

Is it possible to see all connected (Android) devices and select which I want to build the app to?

This would really fit my use-case, and the rest of this library is very robust, so it would be great to include it in my solution!

Thank you, 
Seb

**Comment by robinnorth** [comment]
Hey @Sebight, thanks for your patience in waiting for a reply. That currently isn't possible and I'm not sure how feasible it would be add to the build tool, I'm afraid.

You could, however, try writing a build action to run an interactive shell script that presented the user with the list of connected devices (by grabbing the output of `adb devices` and turning them into options) and allowed them to choose which one(s) to `adb push` the build APK to.
