### ISSUE TITLE
Any plans to add console platform support? (Nintendo Switch, etc)

### ISSUE THREAD

**Issue by 3ternal** [superunitybuild/buildtool#90]
I've been using SuperUnityBuild for desktop platforms for a while, and it's been great. Just wondering if there are any plans to include consoles as target platforms, or if there's any documentation about how to add our own target platforms. Thanks.

**Comment by Chaser324** [comment]
There's relatively fewer people building for those platforms compared to desktop and mobile OS, so I'd never bothered to do anything along those lines. However, it would really just be a matter of defining a new BuildPlatform subclass - see here for examples of all existing platforms: https://github.com/superunitybuild/buildtool/tree/master/Editor/Build/Platform

**Comment by 3ternal** [comment]
Thanks! I tried making one just now and it appears to be working for me.
